[package]
name = "edwar/testingagain"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Comm = "sleitnick/comm@0.2.2"
Component = "sleitnick/component@2.4.0"
EnumList = "sleitnick/enum-list@2.0.0"
Input = "sleitnick/input@1.3.0"
Loader = "sleitnick/loader@1.0.2"
Log = "sleitnick/log@0.1.0"
Option = "sleitnick/option@1.0.3"
PID = "sleitnick/pid@1.0.1"
Ser = "sleitnick/ser@1.0.4"
Shake = "sleitnick/shake@0.1.2"
Signal = "sleitnick/signal@1.1.0"
Streamable = "sleitnick/streamable@1.2.0"
Symbol = "sleitnick/symbol@2.0.0"
TableUtil = "sleitnick/table-util@1.1.1"
TaskQueue = "sleitnick/task-queue@0.1.0"
Timer = "sleitnick/timer@1.1.0"
Trove = "sleitnick/trove@0.1.3"
WaitFor = "sleitnick/wait-for@0.2.0"